#!/usr/bin/env python3
"""
brand/tools/outline-wordmark.py — turn the wordmark into paths.

    python3 brand/tools/outline-wordmark.py > brand/wordmark.mjs

The lockup has to survive being loaded as an <img> on GitHub, on npm and on
the studio page. An SVG in an <img> is an isolated document: it cannot reach
the page's @font-face, and inlining the font to work around that costs a few
hundred KB on every load. Outlines cost a few KB and render identically
everywhere. This runs only when the wordmark text or typeface changes.

Needs fonttools.
"""
import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

FONT = "/usr/share/fonts/truetype/jetbrains-mono/JetBrainsMono-ExtraBold.ttf"
TEXT = "sub-engine"
SIZE = 128.0          # the size the paths are authored at
SLUG = "sub-engine"


def outline():
    font = TTFont(FONT)
    glyphset = font.getGlyphSet()
    cmap = font.getBestCmap()
    upem = font["head"].unitsPerEm
    scale = SIZE / upem
    flip = Transform(scale, 0, 0, -scale, 0, 0)   # font y is up, SVG y is down

    glyphs, advance = [], 0.0
    for ch in TEXT:
        name = cmap[ord(ch)]
        pen = SVGPathPen(glyphset)
        bounds = BoundsPen(glyphset)
        glyphset[name].draw(TransformPen(pen, flip))
        glyphset[name].draw(TransformPen(bounds, flip))
        glyphs.append((advance, pen.getCommands(), bounds.bounds))
        advance += glyphset[name].width * scale

    # The bounds pens above see each glyph at the origin; shift each box by
    # that glyph's advance before taking the union, or the ink box collapses
    # to the width of a single letter.
    boxes = [(b[0] + dx, b[1], b[2] + dx, b[3]) for dx, _, b in glyphs if b]
    minx = min(b[0] for b in boxes)
    maxx = max(b[2] for b in boxes)
    miny = min(b[1] for b in boxes)
    maxy = max(b[3] for b in boxes)

    parts = []
    for dx, d, _ in glyphs:
        if d:
            parts.append(f'<path transform="translate({dx:.2f} 0)" d="{d}"/>')
    return (
        f'<g transform="translate({-minx:.2f} {-miny:.2f})">' + "".join(parts) + "</g>",
        maxx - minx,
        maxy - miny,
        advance,
    )


def main():
    paths, width, height, advance = outline()
    sys.stdout.write(
        "/**\n"
        " * GENERATED by brand/tools/outline-wordmark.py — do not hand-edit.\n"
        f" * Source: JetBrains Mono ExtraBold, the string {TEXT!r}.\n"
        " * Regenerate only when the wordmark text or typeface changes.\n"
        " */\n\n"
        f"export const WORDMARK_TEXT = {TEXT!r};\n\n"
        "/** Ink box of the wordmark: 0,0 is the top-left of the drawn glyphs. */\n"
        f"export const WORDMARK = {{\n"
        f"  paths: {paths!r},\n"
        f"  width: {width:.2f},\n"
        f"  height: {height:.2f},\n"
        f"  advance: {advance:.2f},\n"
        f"  aspect: {width / height:.4f},\n"
        f"}};\n"
    )


if __name__ == "__main__":
    main()